"""Regenerate docs/EXTRACTION-BENCHMARK.md from a live measurement.

    python -m tests.corpus.report

The numbers in that file are never typed by hand. Everything below reads from
the same `measure()` the test enforces, so the documented figure and the
enforced floor cannot drift apart.
"""
from __future__ import annotations

import platform
import subprocess
import sys
from datetime import date
from pathlib import Path

from app.config import settings
from app.ioc import extract
from app.tlds import GENERIC

from .benchmark import time_lines, time_one_paste
from .generate import FORMATS, build_corpus
from .measure import measure

DOCS = Path(__file__).resolve().parents[3] / "docs" / "EXTRACTION-BENCHMARK.md"


def _commit() -> str:
    try:
        return subprocess.check_output(
            ["git", "rev-parse", "--short", "HEAD"], text=True, stderr=subprocess.DEVNULL
        ).strip()
    except (OSError, subprocess.CalledProcessError):
        return "unknown"


def build() -> str:
    settings.allow_documentation_ranges = True
    corpus = build_corpus()
    result = measure(corpus)
    extract("warm 192.0.2.1 example.com https://example.net/a")

    trapped = [line for line in corpus if line.traps]
    traps = sum(len(line.traps) for line in corpus)
    o = result.overall

    rows = []
    for fmt in sorted(result.per_format):
        s = result.per_format[fmt]
        rows.append(
            f"| `{fmt}` | {s.lines:,} | {s.tp:,} | {s.precision:.1%} | "
            f"{s.recall:.1%} | {s.fp} | {s.fn} |"
        )

    sizes = [1000, 2500, 5000, 10000]
    line_rows, paste_rows = [], []
    for size in sizes:
        r = time_lines(size)
        line_rows.append(
            f"| {r.lines:,} | {r.lines_per_second:,.0f} | {r.indicators_per_second:,.0f} "
            f"| {r.percentile(.50):.3f} | {r.percentile(.95):.3f} | "
            f"{r.percentile(.99):.3f} | {r.peak_kib:,.0f} |"
        )
    base = None
    for size in sizes:
        n, secs, found = time_one_paste(size)
        per_line = secs / n
        base = base or per_line
        paste_rows.append(
            f"| {n:,} | {secs:.3f} | {n / secs:,.0f} | {found:,} | {per_line / base:.2f} |"
        )

    nl = "\n"
    return f"""# Extraction accuracy and throughput

*Generated by `python -m tests.corpus.report` — do not edit by hand.*

| | |
|---|---|
| Date | {date.today().isoformat()} |
| Commit | `{_commit()}` |
| Python | {platform.python_version()} |
| Platform | {platform.system()} {platform.machine()} |

## What is being measured

{len(corpus):,} log lines generated across {len(result.per_format)} formats by
{len(FORMATS)} generators, each carrying the exact set of indicators the
extractor is contracted to return. Every value is synthetic: addresses come from
RFC 5737 documentation space and hostnames from RFC 2606 reserved names, so
nothing in the corpus can be resolved or contacted. The framing — the ASA
severity code, the Zeek column order, the PAN-OS comma inside a quoted field —
is what those products actually emit, and that framing is the part under test.

{len(trapped):,} of the {len(corpus):,} lines ({len(trapped) / len(corpus):.0%})
carry at least one trap: {traps:,} values that look extractable and must not be.
Private and carrier-grade-NAT addresses, filenames with domain-shaped
extensions, and version strings. Precision measured without traps means nothing.

Ground truth is the documented contract, not the extractor's own output. Where
the implementation disagrees with the expectation, the disagreement is reported
as a miss or a false positive — which is how the five findings below were found.

## Accuracy

**Precision {o.precision:.1%} · Recall {o.recall:.1%}** over {o.tp + o.fn:,}
expected indicators ({o.tp:,} true positives, {o.fp} false positives,
{o.fn} missed).

| Format | Lines | Found | Precision | Recall | FP | Missed |
|---|---:|---:|---:|---:|---:|---:|
{nl.join(rows)}

Traps sprung: **{sum(result.sprung_traps.values())}**. Zero is enforced by
`test_no_trap_is_ever_sprung` rather than reported — a sprung trap is an
internal address or an employee's filename being sent to a third-party API, not
a rounding error in a score.

## Throughput

One line at a time, as `/api/triage` is driven:

| Lines | Lines/s | Indicators/s | p50 ms | p95 ms | p99 ms | Peak KiB |
|---:|---:|---:|---:|---:|---:|---:|
{nl.join(line_rows)}

The whole corpus as a single paste, as `/api/triage/upload` is driven:

| Lines | Seconds | Lines/s | Indicators | Cost/line vs smallest |
|---:|---:|---:|---:|---:|
{nl.join(paste_rows)}

The last column is the linearity check: 1.0 means a paste ten times larger costs
ten times as much and no more. Before the fix described below it reached 2.97.

Timing and memory are measured in separate passes. `tracemalloc` traces every
allocation and costs roughly 7x, so running it around the timing loop produces a
throughput figure that describes the profiler rather than the parser.

## What this found

Five bugs, each pinned by name in `tests/test_extraction_findings.py`:

1. **Carrier-grade NAT was queried as public space** (158 occurrences). The
   README promised CGNAT was dropped; Python's `ipaddress` does not flag
   100.64.0.0/10, so it never was.
2. **Usernames were read as domains** (318). `j.doe` matched the domain pattern
   and `doe` was not on the file-extension denylist, so an employee's username
   was sent to a threat-intel vendor.
3. **File extensions were read as TLDs** (150+). `x.php`, `index.html`,
   `core.dmp`, `web.config`. A denylist of things that are not TLDs can never be
   complete, so the check now tests membership of the published TLD list
   ({len(GENERIC):,} entries).
4. **The allowlist then swallowed real TLDs.** `.zip`, `.mov` and `.sh` are live
   TLDs *and* file extensions, and are registered by attackers for exactly that
   reason. Position resolves it: a label in a URL host or after an `@` is
   declared to be a hostname and keeps the domain reading; a bare token in a log
   line does not.
5. **A 5 MB upload took 14.1 seconds and blocked the event loop.** Masking URLs
   with one `str.replace` per URL, and re-finding each indicator's offset with
   `str.find`, each rescanned the whole input per match. Both are single-pass
   now; the same upload takes 1.4 seconds and `test_extraction_scaling.py` keeps
   it that way.

Findings 1 through 3 shipped. Finding 4 was introduced by the fix for 3 and
caught by probing the fix with real-world hostnames the corpus does not contain.
Finding 5 was found by the benchmark, not the corpus.
"""


def main() -> None:
    DOCS.parent.mkdir(parents=True, exist_ok=True)
    DOCS.write_text(build(), encoding="utf-8")
    print(f"wrote {DOCS}", file=sys.stderr)


if __name__ == "__main__":
    main()
