#!/usr/bin/env python3
"""Build every logo asset from docs/logo.svg.

    python docs/make_logo.py

writes
    docs/logo.png                   512 px emblem
    docs/banner.png                 README header (emblem + wordmark)
    src/phishhawk/_logo_art.py      the terminal banner: ASCII-art emblem
                                    plus figlet "basic" lettering

Needs cairosvg, Pillow and pyfiglet at build time only; the generated module
is plain data, so the installed tool has no extra dependencies.
"""

from __future__ import annotations

import io
import os
import re

import cairosvg
import pyfiglet
from PIL import Image

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
with open(os.path.join(HERE, "logo.svg"), encoding="utf-8") as _svg:
    SVG = _svg.read()

COLS, ROWS = 36, 18          # emblem size in terminal cells
CELL_W, CELL_H = 10, 20      # pixels sampled per cell (cells are ~2:1)
DARK = 70                    # luminance below which a pixel is a cut-out line
EDGE = " .:-=+"              # partial-coverage glyphs, light to heavy
# Interior texture: pairs are alternated in a checkerboard, which gives the
# woven "V1V1" look of classic ASCII-art converters.
BODY = [("v", "1"), ("V", "1"), ("U", "V"), ("X", "U"), ("%", "X"), ("#", "%"), ("@", "#")]


def rgb_to_xterm(r: int, g: int, b: int) -> int:
    """Nearest xterm-256 colour (6x6x6 cube or the grey ramp)."""
    def cube(v: int) -> int:
        return 0 if v < 48 else (1 if v < 115 else (v - 35) // 40)
    ri, gi, bi = cube(r), cube(g), cube(b)
    levels = [0, 95, 135, 175, 215, 255]
    cube_rgb = (levels[ri], levels[gi], levels[bi])
    grey = sum((r, g, b)) // 3
    gi_ = 23 if grey > 238 else max(0, (grey - 3) // 10)
    grey_rgb = (8 + 10 * gi_,) * 3
    dist = lambda a: sum((x - y) ** 2 for x, y in zip(a, (r, g, b), strict=True))  # noqa: E731
    return 232 + gi_ if dist(grey_rgb) < dist(cube_rgb) else 16 + 36 * ri + 6 * gi + bi


def emblem_image() -> Image.Image:
    svg = re.sub(r'<rect [^>]*fill="#0b1220"/>', "", SVG)               # transparent background
    svg = svg.replace('viewBox="0 0 200 200"', 'viewBox="20 40 170 148"')  # crop to the head
    png = cairosvg.svg2png(bytestring=svg.encode(), output_width=COLS * CELL_W,
                           output_height=ROWS * CELL_H)
    return Image.open(io.BytesIO(png)).convert("RGBA")


def ascii_emblem() -> tuple[list[str], list[list[int]]]:
    img = emblem_image()
    chars: list[str] = []
    colours: list[list[int]] = []
    for row in range(ROWS):
        line, tones = "", []
        for col in range(COLS):
            box = (col * CELL_W, row * CELL_H, (col + 1) * CELL_W, (row + 1) * CELL_H)
            pixels = list(img.crop(box).get_flattened_data())
            lit = [p for p in pixels if p[3] > 128 and 0.3 * p[0] + 0.59 * p[1] + 0.11 * p[2] > DARK]
            cover = len(lit) / len(pixels)
            if cover < 0.10:
                line += " "
                tones.append(0)
                continue
            r = sum(p[0] for p in lit) // len(lit)
            g = sum(p[1] for p in lit) // len(lit)
            b = sum(p[2] for p in lit) // len(lit)
            luminance = 0.3 * r + 0.59 * g + 0.11 * b
            if b > r + 40:                       # the cyan eye
                glyph = "O" if cover > 0.5 else "o"
            elif abs(r - b) < 40 and r > 120:    # the steel beak
                glyph = "#" if cover > 0.6 else ":"
            elif cover < 0.55:
                glyph = EDGE[min(len(EDGE) - 1, int(cover * len(EDGE) * 1.6))]
            else:
                pair = BODY[min(len(BODY) - 1, int((luminance - 90) / 150 * len(BODY)))]
                glyph = pair[(row + col) % 2]
            line += glyph
            tones.append(rgb_to_xterm(r, g, b))
        chars.append(line)
        colours.append(tones)
    return chars, colours


def figlet(word: str) -> list[str]:
    lines = pyfiglet.figlet_format(word, font="basic").rstrip("\n").split("\n")
    lines = [line.rstrip() for line in lines]
    while lines and not lines[-1]:
        lines.pop()
    return lines


def write_module(chars, colours) -> None:
    path = os.path.join(ROOT, "src", "phishhawk", "_logo_art.py")
    with open(path, "w", encoding="utf-8") as out:
        out.write('"""Generated by docs/make_logo.py from docs/logo.svg. Do not edit by hand."""\n\n')
        out.write("# fmt: off\n")
        out.write("EMBLEM = [\n")
        for line in chars:
            out.write("    %r,\n" % line)
        out.write("]\n\n")
        out.write("# xterm-256 colour per cell of EMBLEM (0 = blank)\n")
        out.write("EMBLEM_COLOURS = [\n")
        for tones in colours:
            out.write("    [%s],\n" % ", ".join(str(t) for t in tones))
        out.write("]\n\n")
        for name, word in (("PHISH", "PHISH"), ("HAWK", "HAWK")):
            out.write("%s = [\n" % name)
            for line in figlet(word):
                out.write("    %r,\n" % line)
            out.write("]\n\n")
        out.write("# fmt: on\n")
    print("wrote", os.path.relpath(path, ROOT))


def write_pngs() -> None:
    cairosvg.svg2png(bytestring=SVG.encode(), write_to=os.path.join(HERE, "logo.png"),
                     output_width=512, output_height=512)
    print("wrote docs/logo.png")


if __name__ == "__main__":
    art, tones = ascii_emblem()
    write_module(art, tones)
    write_pngs()
    print("\n".join(art))
