"""Markdown ticket note: paste straight into Jira, ServiceNow or TheHive."""

from __future__ import annotations

from .. import __version__
from ..extract import defang_host, defang_url
from ..models import Analysis
from .common import recommendations, sorted_signals, summary_sentences, technique_rows, utc_now


def _cell(text: str) -> str:
    return str(text).replace("|", "\\|").replace("\n", " ")


def _defang_ioc(ioc: dict) -> str:
    if ioc["type"] == "url":
        return defang_url(ioc["value"])
    if ioc["type"] == "sha256":
        return ioc["value"]
    return defang_host(ioc["value"])


def render(a: Analysis) -> str:
    out = ["## Phishing triage: %s (risk score %d)" % (a.verdict, a.score), ""]
    out.append("| | |")
    out.append("|---|---|")
    out.append("| **Subject** | %s |" % _cell(a.subject or "(none)"))
    out.append("| **From** | %s `%s` |" % (_cell(a.from_display), defang_host(a.from_address)))
    if a.reply_to:
        out.append("| **Reply-To** | `%s` |" % defang_host(a.reply_to))
    if a.originating_ip:
        out.append("| **Originating IP** | `%s` |" % defang_host(a.originating_ip))
    if a.auth:
        out.append("| **Authentication** | %s |" % " · ".join(
            "%s %s" % (k.upper(), v) for k, v in a.auth.items()))
    out.append("| **Message-ID** | `%s` |" % _cell(a.message_id or "(none)"))
    if a.reported_by:
        out.append("| **Reported by** | %s |" % _cell(a.reported_by.get("from", "")))
    out += ["", "**Summary:** " + " ".join(summary_sentences(a)), ""]

    signals = sorted_signals(a)
    if signals:
        out += ["### Key findings", ""]
        for signal in signals[:15]:
            tags = " (%s)" % ", ".join(signal.techniques) if signal.techniques else ""
            out.append("- **%s**: %s%s" % (signal.severity.upper(), signal.label, tags))
        if len(signals) > 15:
            out.append("- ... %d lower-priority findings in the full report" % (len(signals) - 15))
        out.append("")

    iocs = a.iocs()
    if iocs:
        out += ["### Indicators (defanged)", "", "| Type | Value | Context |", "|---|---|---|"]
        out += ["| %s | `%s` | %s |" % (i["type"], _cell(_defang_ioc(i)), _cell(i["context"])) for i in iocs]
        out.append("")

    rows = technique_rows(a)
    if rows:
        out += ["### MITRE ATT&CK", ""]
        out += ["- [%s](%s) %s" % (row["id"], row["url"], row["name"]) for row in rows]
        out.append("")

    out += ["### Recommended actions", ""]
    out += ["- [ ] %s" % action for action in recommendations(a)]
    out += ["", "_Generated by phishtriage %s at %s_" % (__version__, utc_now()), ""]
    return "\n".join(out)
