#!/usr/bin/env python3
"""Run PhishHawk straight from a checkout, without installing it:

    ./phishhawk suspicious.eml
"""

import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(os.path.realpath(__file__)), "src"))

from phishhawk.cli import run  # noqa: E402

run()
